NSGA_settings:
  mut_eta: 20
  n_eval: 40000
  n_offsprings: 92
  pop_size: 1000
  ref_dirs: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 91
      - 3
    - !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAAAABVVVVVVVW1P1VVVVVVVe0/AAAAAAAAAABV
      VVVVVVXFP6uqqqqqquo/AAAAAAAAAAAAAAAAAADQPwAAAAAAAOg/AAAAAAAAAABVVVVVVVXVP1VV
      VVVVVeU/AAAAAAAAAACrqqqqqqraP6uqqqqqquI/AAAAAAAAAAAAAAAAAADgPwAAAAAAAOA/AAAA
      AAAAAACrqqqqqqriP6uqqqqqqto/AAAAAAAAAABVVVVVVVXlP1VVVVVVVdU/AAAAAAAAAAAAAAAA
      AADoPwAAAAAAANA/AAAAAAAAAACrqqqqqqrqP1VVVVVVVcU/AAAAAAAAAABVVVVVVVXtP1VVVVVV
      VbU/AAAAAAAAAAAAAAAAAADwPwAAAAAAAAAAVVVVVVVVtT8AAAAAAAAAAFVVVVVVVe0/VVVVVVVV
      tT9VVVVVVVW1P6uqqqqqquo/VVVVVVVVtT9VVVVVVVXFPwAAAAAAAOg/VVVVVVVVtT8AAAAAAADQ
      P1VVVVVVVeU/VVVVVVVVtT9VVVVVVVXVP6uqqqqqquI/VVVVVVVVtT+rqqqqqqraPwAAAAAAAOA/
      VVVVVVVVtT8AAAAAAADgP6uqqqqqqto/VVVVVVVVtT+rqqqqqqriP1VVVVVVVdU/VVVVVVVVtT9V
      VVVVVVXlPwAAAAAAANA/VVVVVVVVtT8AAAAAAADoP1VVVVVVVcU/VVVVVVVVtT+rqqqqqqrqP1VV
      VVVVVbU/VVVVVVVVtT9VVVVVVVXtPwAAAAAAAAAAVVVVVVVVxT8AAAAAAAAAAKuqqqqqquo/VVVV
      VVVVxT9VVVVVVVW1PwAAAAAAAOg/VVVVVVVVxT9VVVVVVVXFP1VVVVVVVeU/VVVVVVVVxT8AAAAA
      AADQP6uqqqqqquI/VVVVVVVVxT9VVVVVVVXVPwAAAAAAAOA/VVVVVVVVxT+rqqqqqqraP6uqqqqq
      qto/VVVVVVVVxT8AAAAAAADgP1VVVVVVVdU/VVVVVVVVxT+rqqqqqqriPwAAAAAAANA/VVVVVVVV
      xT9VVVVVVVXlP1VVVVVVVcU/VVVVVVVVxT8AAAAAAADoP1VVVVVVVbU/VVVVVVVVxT+rqqqqqqrq
      PwAAAAAAAAAAAAAAAAAA0D8AAAAAAAAAAAAAAAAAAOg/AAAAAAAA0D9VVVVVVVW1P1VVVVVVVeU/
      AAAAAAAA0D9VVVVVVVXFP6uqqqqqquI/AAAAAAAA0D8AAAAAAADQPwAAAAAAAOA/AAAAAAAA0D9V
      VVVVVVXVP6uqqqqqqto/AAAAAAAA0D+rqqqqqqraP1VVVVVVVdU/AAAAAAAA0D8AAAAAAADgPwAA
      AAAAANA/AAAAAAAA0D+rqqqqqqriP1VVVVVVVcU/AAAAAAAA0D9VVVVVVVXlP1VVVVVVVbU/AAAA
      AAAA0D8AAAAAAADoPwAAAAAAAAAAVVVVVVVV1T8AAAAAAAAAAFVVVVVVVeU/VVVVVVVV1T9VVVVV
      VVW1P6uqqqqqquI/VVVVVVVV1T9VVVVVVVXFPwAAAAAAAOA/VVVVVVVV1T8AAAAAAADQP6uqqqqq
      qto/VVVVVVVV1T9VVVVVVVXVP1VVVVVVVdU/VVVVVVVV1T+rqqqqqqraPwAAAAAAANA/VVVVVVVV
      1T8AAAAAAADgP1VVVVVVVcU/VVVVVVVV1T+rqqqqqqriP1VVVVVVVbU/VVVVVVVV1T9VVVVVVVXl
      PwAAAAAAAAAAq6qqqqqq2j8AAAAAAAAAAKuqqqqqquI/q6qqqqqq2j9VVVVVVVW1PwAAAAAAAOA/
      q6qqqqqq2j9VVVVVVVXFP6uqqqqqqto/q6qqqqqq2j8AAAAAAADQP1VVVVVVVdU/q6qqqqqq2j9V
      VVVVVVXVPwAAAAAAANA/q6qqqqqq2j+rqqqqqqraP1VVVVVVVcU/q6qqqqqq2j8AAAAAAADgP1VV
      VVVVVbU/q6qqqqqq2j+rqqqqqqriPwAAAAAAAAAAAAAAAAAA4D8AAAAAAAAAAAAAAAAAAOA/AAAA
      AAAA4D9VVVVVVVW1P6uqqqqqqto/AAAAAAAA4D9VVVVVVVXFP1VVVVVVVdU/AAAAAAAA4D8AAAAA
      AADQPwAAAAAAANA/AAAAAAAA4D9VVVVVVVXVP1VVVVVVVcU/AAAAAAAA4D+rqqqqqqraP1VVVVVV
      VbU/AAAAAAAA4D8AAAAAAADgPwAAAAAAAAAAq6qqqqqq4j8AAAAAAAAAAKuqqqqqqto/q6qqqqqq
      4j9VVVVVVVW1P1VVVVVVVdU/q6qqqqqq4j9VVVVVVVXFPwAAAAAAANA/q6qqqqqq4j8AAAAAAADQ
      P1VVVVVVVcU/q6qqqqqq4j9VVVVVVVXVP1VVVVVVVbU/q6qqqqqq4j+rqqqqqqraPwAAAAAAAAAA
      VVVVVVVV5T8AAAAAAAAAAFVVVVVVVdU/VVVVVVVV5T9VVVVVVVW1PwAAAAAAANA/VVVVVVVV5T9V
      VVVVVVXFP1VVVVVVVcU/VVVVVVVV5T8AAAAAAADQP1VVVVVVVbU/VVVVVVVV5T9VVVVVVVXVPwAA
      AAAAAAAAAAAAAAAA6D8AAAAAAAAAAAAAAAAAANA/AAAAAAAA6D9VVVVVVVW1P1VVVVVVVcU/AAAA
      AAAA6D9VVVVVVVXFP1VVVVVVVbU/AAAAAAAA6D8AAAAAAADQPwAAAAAAAAAAq6qqqqqq6j8AAAAA
      AAAAAFVVVVVVVcU/q6qqqqqq6j9VVVVVVVW1P1VVVVVVVbU/q6qqqqqq6j9VVVVVVVXFPwAAAAAA
      AAAAVVVVVVVV7T8AAAAAAAAAAFVVVVVVVbU/VVVVVVVV7T9VVVVVVVW1PwAAAAAAAAAAAAAAAAAA
      8D8AAAAAAAAAAAAAAAAAAAAA
  sbx_eta: 30
  sbx_prob: 1
cluster_pf_required: true
clustering_config:
  MSE_threshold: 0.0002
  max_clusters: 4
  min_cluster_size: 2
n_clusters: 2
non_rand_regularity_MSE_threshold: 0.1
non_rand_regularity_degree: 1
pf_cluster_eps: null
precision: 2
rand_factor_sd: 0.1
rand_regularity_MSE_threshold: 0.1
rand_regularity_coef_factor: 0.1
rand_regularity_dependency: 1
