NSGA_settings:
  mut_eta: 20
  n_eval: 40000
  n_offsprings: 30
  pop_size: 200
  sbx_eta: 30
  sbx_prob: 1
cluster_pf_required: true
clustering_config:
  MSE_threshold: 0.0002
  max_clusters: 4
  min_cluster_size: 2
n_clusters: 1
non_rand_regularity_MSE_threshold: 0.1
non_rand_regularity_degree: 1
pf_cluster_eps: null
precision: 2
rand_factor_sd: 0.2
rand_regularity_MSE_threshold: 0.1
rand_regularity_coef_factor: 0.1
rand_regularity_dependency: 1
