#python3 -m regemo.algorithm.regularity_driver --problem_name conceptual_marine_design
#python3 -m regemo.algorithm.regularity_driver --problem_name bnh
#python3 -m regemo.algorithm.regularity_driver --problem_name c2dtlz2
#python3 -m regemo.algorithm.regularity_driver --problem_name dtlz2
#python3 -m regemo.algorithm.regularity_driver --problem_name dtlz5
#python3 -m regemo.algorithm.regularity_driver --problem_name dtlz7
#python3 -m regemo.algorithm.regularity_driver --problem_name mod_zdt
#python3 -m regemo.algorithm.regularity_driver --problem_name osy
#python3 -m regemo.algorithm.regularity_driver --problem_name srn
#python3 -m regemo.algorithm.regularity_driver --problem_name two_member_truss
#python3 -m regemo.algorithm.regularity_driver --problem_name welded_beam_design
#python3 -m regemo.algorithm.regularity_driver --problem_name four_bar_truss_design
#python3 -m regemo.algorithm.regularity_driver --problem_name reinforced_concrete_beam_design
#python3 -m regemo.algorithm.regularity_driver --problem_name pressure_vessel_design
#python3 -m regemo.algorithm.regularity_driver --problem_name hatch_cover_design
#python3 -m regemo.algorithm.regularity_driver --problem_name disk_brake_design
#python3 -m regemo.algorithm.regularity_driver --problem_name hatch_cover_design
python3 -m regemo.algorithm.regularity_driver --problem_name tnk