#python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name bnh
#python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name c2dtlz2
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name dtlz2
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name osy
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name zdt_mod_2d
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name zdt_mod_3d
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name conceptual_marine_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name dtlz5
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name dtlz7
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name srn
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name two_member_truss
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name four_bar_truss_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name reinforced_concrete_beam_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name pressure_vessel_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name hatch_cover_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name disk_brake_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name tnk
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name coil_compression_spring_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name speed_reducer_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name gear_train_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name rocket_injector_design
python3 -m regemo.algorithm.regularity_driver_nsga2 --problem_name car_side_impact
