clustering_config:
  criterion: X
dim: 12
lb:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
n_clusters: 1
n_constr: 1
n_obj: 3
name: c2dtlz2
ub:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
visualization_angle: !!python/tuple
- 45
- 45
